const rankAvatarThemes = [
  "bg-white text-black",
  "bg-orange-500 text-white",
  "bg-green-300 text-black",
  "bg-blue-600 text-black",
  "bg-purple-700 text-black",
  "bg-pink-200 text-black",
  "bg-pink-300 text-black",
  "bg-gray-300 text-black",
  "bg-blue-300 text-black",
  "bg-orange-300 text-black",
  "bg-purple-300 text-black",
  "bg-indigo-300 text-black",
  "bg-sky-400 text-black",
  "bg-lime-400 text-black",
  "bg-fuchsia-500 text-black",
  "bg-violet-500 text-black",
  "bg-rose-500 text-black",
  "bg-yellow-300 text-black",
  "bg-red-600 text-black",
  "bg-amber-200 text-black",
  "bg-emerald-400 text-black",
];

export { rankAvatarThemes };